name = "wtinyradio-data"
main = "src/index.js"
compatibility_date = "2026-07-13"
workers_dev = true

routes = [
  { pattern = "radio-api.wtinyradio.com", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "wtinyradio-chat"
database_id = "77c7c75b-3edf-40eb-a3c7-6a76be17fbd9"

